extends: stezu
rules:

  # Reflect is not available in Node 4
  prefer-reflect: "off"

  # Rest params is not available in Node 4
  prefer-rest-params: "off"

  # Enforce valid JSDoc comments
  # http://eslint.org/docs/rules/valid-jsdoc
  valid-jsdoc:
    - error

  # Require JSDoc comments
  # http://eslint.org/docs/rules/require-jsdoc
  require-jsdoc:
    - error
    - require:
        FunctionDeclaration: true
        MethodDefinition: true
        ClassDeclaration: true
