language: node_js
node_js:
  - node
  - "8"
  - "6"
  - "4"
script:
  - npm run ci
after_script:
  - cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
deploy:
  - provider: npm
    email: hello@stephenzuniga.com
    api_key:
      secure: CfVAXnQmh7VZzzsezz3OINHC+qfMhHENuyOVWcwqZXuswl6U2U16xYcpls/GmX+9OxPgGGa5JSHYvkdYejWsVxsvU0K89sQLLTm3+FpFYxvMKhaw8Ak481UwLCRq5JlHG7r1EK4chNSKFLpYaBCGPLKHg24TC/3qUYSUx+2rwwyUytuZ15Sxd8/LK2NKdzQLVFlQnhCkZikZtyUIPcRfBNRWb0byrJEYCYUZcJqKb34UTAS4Uymwj9Vno09YBF3j3p43xd5Tsi23aiqNecmO5zpmqC3ONAXCIyin2hXTAbZ3vmAn+6XyZms2Z7end5mpRk88XaLteCzOQOU9uFJRmqult56uHxpQo8XAmsmTIFYZMaeavXT2F2H3fVyfSxNreoZvlajNEUFqE8G2icA3t0oLkUCiUVzcXy2Ow7ArHQcyMfOT94/4hsEWLrG7R3nxojXfqkTbr16uewmP+S9gMnnoaRSfagheiKMypqYatPB8ZkNblMOPbG4epN+H+hbhkWGl39+cf7TanbgeFbmRs0WE/YxU8NaQVYE3SbqEot9gXIbdrinclk9hFdA5b1/pduCIbpPWreqaZkvjmtNi0M/XTER7n5FFX8JjTIKZK9CDYevPRjVLcbS9v7UkysvqMBu1XSX2iH3wJBGJBNZ0Rdu2A1M8HdoZh+ACHIFVdoQ=
    on:
      tags: true
      node: "8"
      repo: stezu/node-stream
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: docs
    on:
      tags: true
      node: "8"
      repo: stezu/node-stream
